name = "notes-app"
pages_build_output_dir = "www"
compatibility_date = "2025-01-06"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "notes"
database_id = "0401829d-c3dd-4c2f-93cd-88f67677a1ed"


